version: '3.3'

services:
  app:
    build: pluto
    restart: ${RESTART:-no}
    volumes:
      - ./:/app
    working_dir: /app/pluto
    ports:
      - "${BACKEND_HOST_PORT}8000"
    stdin_open: true
    tty: true
    networks:
      - app-newtwork

    command: ${RUNSERVER:-/bin/bash}

networks:
  app-newtwork: null
