# Generated by Django 3.2.10 on 2021-12-10 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starfish', '0002_auto_20211210_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='team',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='starfish.team',
                verbose_name='Time'),
        ),
    ]
